README.md
The command provided in README to bootstrap the config is not correct (seems to be legacy from "rubocop-rails").
=> Update README.md to fix install command

config/rails.yml
Exclude ruby files in `db` directory. Otherwise, `schema.rb` gets offences:
```
Offenses:
db/schema.rb:14:1: C: [Corrected] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body beginning.
db/schema.rb:48:1: C: [Corrected] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.
```
=> Exclude Ruby files in db directory

config/rails.yml
ref. https://github.com/toshimaru/rubocop-rails/issues/15
After running `rails app:update`,  it generates many files which have rubocop offense. Let's ignore the files.
=> Update Exclude Setting

README.md
RubyCop is the proper notation as below.
> **RuboCop** is a Ruby static code analyzer and code formatter.
> Out of the box it will enforce many of the guidelines outlined
> in the community Ruby Style Guide.
https://github.com/rubocop-hq/rubocop/blob/v0.65.0/README.md
=> Unify the notation of RuboCop

config/rails.yml, lib/generators/rubocop_rails_config/install_generator.rb, lib/generators/rubocop_rails_config/update_generator.rb
Follow up https://github.com/rails/rails/pull/36472.
This PR enables `Layout/EmptyLinesAroundAccessModifier` cop with `EnforcedStyle: only_before`.
This enforced style was introduced with RuboCop 0.70.
https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#0700-2019-05-21
=> Enable `Layout/EmptyLinesAroundAccessModifier` cop

config/rails.yml
Just a reintroduction.
This was removed with the last update.
I would like to reintroduce it for several reasons:
* rubocop now complains about Migrations but I can't change them because you never change Migrations.
* Also they are generated and not written by humans most of the Time.
* Rubocop complaint about db/schema.rb (missing Frozen String Literal) and you should never change that File by Hand...
* bin/* Files are also not written by Humans most of the Time. I see no reason to Lint them.
* Mostly same for the Files in config/ (but I could Argue on those...)
=> Exclude bin/ db/ and config/ from Lint

.travis.yml, Appraisals, config/rails.yml, gemfiles/rubocop_0.76.gemfile, rubocop-rails_config.gemspec
Fixes #56.
This PR supports RuboCop 0.76 and renames `Style/UnneededPercentQ` cop to `Style/RedundantPercentQ` cop.
https://github.com/rails/rails/pull/37582 has not yet been merged.
However, this change is absolutely necessary. So, I'd like to merge and release first for the convenience of rubocop-rails_config users.
=> Support RuboCop 0.76

.travis.yml, README.md, config/rails.yml, rubocop-rails_config.gemspec
RuboCop 0.82 has been released. It drops Ruby 2.3.
https://github.com/rubocop-hq/rubocop/releases/tag/v0.82.0
=> Drop support for Ruby 2.3

config/rails.yml
Follow up to rails/rails#39409.
This PR enables Performance/DeletePrefix and Performance/DeleteSuffix cops.
=> Enable `Performance/DeletePrefix` and `Performance/DeleteSuffix` cops

config/rails.yml
Follow https://github.com/rails/rails/commit/a908d06.
This PR enables `Style/RedundantRegexpEscape` cop.
=> Enable `Style/RedundantRegexpEscape` cop

rubocop-rails_config.gemspec
Hi @toshimaru,
RuboCop::Packaging through v0.5 supports
autocorrect for its cops. Thus worth bumping
the version from v0.4 to v0.5.
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>
=> Bump RuboCop::Packaging to v0.5

config/rails.yml
Follow https://github.com/rails/rails/commit/ba97e9f918bc2ffe8ed351a0e0b8d75b67d26086.
"shadowing outer local variable" warning was removed in Ruby 2.6.
- ruby/ruby@c9d720b
- https://bugs.ruby-lang.org/issues/12490
rubocop-rails_config supports Ruby 2.4, however rubocop-rails_config is rails/rails repo compliant. If Ruby 2.5 or lower users need `Lint/ShadowingOuterLocalVariable` warning, it can be enabled on the application side.
=> Disable `Lint/ShadowingOuterLocalVariable` cop

config/rails.yml
Follow https://github.com/toshimaru/rubocop-rails_config/pull/48.
I think it is reasonable that auto-generated `db/schema.rb` is excluded by default. But `db/migrate/*.rb` will be user-written and I think `db/**/*` is too wide range.
I noticed that cops couldn't detect offenses because entire `db` directory has been excluded. So, this PR defaults to excluding only `schema.rb` in `db` directory.
=> Exclude only schema.rb in db directory

config/rails.yml
`config` directory contains files that user can write, such as `application.rb`, `environments/*.rb`, and so on.
Like #104, I think these are targets that should be detected offenses by default.
=> Include config directory by default

config/rails.yml
The next version of RuboCop will drop Ruby 2.4 support.
https://github.com/rubocop/rubocop/pull/9648
This PR prevents the following error with edge RuboCop (and next stable RuboCop).
```console
% bundle exec rubocop --parallel
Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion`
parameter (in /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/
rubocop-rails_config-1.4.0/config/rails.yml).
2.4-compatible analysis was dropped after version 1.12.
Supported versions: 2.5, 2.6, 2.7, 3.0
```
The minimum Ruby supported version of the next RuboCop is 2.5.
I think it would be beneficial for both UX and maintainability to omit `TargetRubyVersion` and delegate it to RuboCop core.
=> Relax `TargetRubyVersion`

config/rails.yml, rubocop-rails_config.gemspec
Follow https://github.com/rails/rails/commit/bbbc861
This PR enables `Performance/MapCompact` cop and requires RuboCop Performance 1.11 or higher.
Because `Performance/MapCompact` cop has introduced in RuboCop Performance 1.11.
=> Enable `Performance/MapCompact` cop

config/rails.yml
Follow up https://github.com/rails/rails/pull/45865
This PR enables `Performance/InefficientHashSearch`,  `Performance/ConstantRegexp`, `Performance/RedundantStringChars`, and `Performance/StringInclude`.
=> Enable four Performance cops

rubocop-rails_config.gemspec
Follow up https://github.com/toshimaru/rubocop-rails_config/pull/161.
This PR sets the required_ruby_version to 2.7+.
=> Set the required_ruby_version to 2.7+

Rakefile
This PR fixes the following build error:
```console
(snip)
rubocop --except=Style/StringLiterals,Style/FrozenStringLiteralComment .
cp ./test/fixture/.rubocop.yml rails_test/.rubocop.yml
cd rails_test
Inspecting 28 files
C...........................
Offenses:
Gemfile:71:1: C: [Correctable] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.
28 files inspected, 1 offense detected, 1 offense autocorrectable
rake aborted!
```
https://github.com/toshimaru/rubocop-rails_config/actions/runs/6167995304/job/16739825926
This is a regression in Rails 7.0.8, which will be resolved by https://github.com/rails/rails/pull/49247. Until then, specifying the `Layout/EmptyLinesAroundBlockBody` cop is a workaround to prevent the build error.
=> Fix a build error

config/rails.yml
Follow up https://github.com/rails/rails/pull/49236.
This PR enables `Minitest/LiteralAsActualArgument` cop.
=> Enable `Minitest/LiteralAsActualArgument` cop

config/rails.yml
Follow up https://github.com/rails/rails/pull/49404
This PR enables `Lint/RedundantSafeNavigation` cop.
=> Enable `Lint/RedundantSafeNavigation` cop

rubocop-rails_config.gemspec
`bundle update rubocop-rails_config` unexpectedly upgrades `zweitwerk`, a dependency of `railties` (Dependabot as well). This PR removes `railties` from the runtime dependencies to prevent such unintended gem upgrades.
=> Remove railties from runtime dependencies

Gemfile, gemfiles/rubocop_1.48.gemfile, gemfiles/rubocop_1.49.gemfile, gemfiles/rubocop_1.50.gemfile, gemfiles/rubocop_1.51.gemfile, gemfiles/rubocop_1.52.gemfile, gemfiles/rubocop_1.53.gemfile, gemfiles/rubocop_1.54.gemfile, gemfiles/rubocop_1.55.gemfile, gemfiles/rubocop_1.56.gemfile
This is a workaround to prevent the following error in RuboCop Rails 2.21.2. https://github.com/toshimaru/rubocop-rails_config/actions/runs/6522833241/job/17712818757#step:4:85
`gem "rubocop-rails", "2.21.1"` specification can be removed once a version resolving the issue is released.
=> Workaround to prevent the following error in RuboCop Rails 2.21.2

config/rails.yml, rubocop-rails_config.gemspec
Follow-up https://github.com/rails/rails/pull/54801
This PR bumps rubocop-packaging to 0.6.0 to use the new plugin-based version.
=> Bump rubocop-packaging to 0.6.0
