toshimaru/rubocop-rails_config

config/rails.yml, lib/custom_cops/assert_not.rb, test/custom_cops/assert_not_test.rb, test/custom_cops/refute_not_test.rb
Follow up https://github.com/rails/rails/pull/32605/
=> Add `CustomCops/AssertNot` rule

config/rails.yml
=> Enable `Layout/EmptyLinesAroundBlockBody` cop

config/rails.yml
Follow up of rails/rails#32381.
=> Turn on performance based cops

config/rails.yml
=> Enable Regexp cops

config/rails.yml
=> Enable `Lint/UriEscapeUnescape` cop

config/rails.yml
=> Enable Style/ParenthesesAroundCondition cop

config/rails.yml
=> Enable `Performance/UnfreezeString` cop

config/rails.yml
=> Enable `Style/RedundantFreeze` cop

config/rails.yml
=> Ignore bin/config/db directories

config/rails.yml
Refer https://github.com/rails/rails/commit/f907b418aecfb6dab4e30149b88a8593ddd321b9
=> Enable `Layout/SpaceAfterSemicolon` cop

config/rails.yml
Follow up of rails/rails#34764.
=> Enable `Style/RedundantBegin` cop

config/rails.yml
Refer https://github.com/rails/rails/commit/6d959017bd05c775d35045401292828c92b7dcc7.
=> Enable `Lint/ShadowingOuterLocalVariable` cop

config/rails.yml
Refer https://github.com/rails/rails/pull/34903.
=> Enable `Lint/DeprecatedClassMethods` cop

config/rails.yml
Follow up of https://github.com/rails/rails/commit/6b8daad0383a40bb397644d0a1f8b35808611d6e.
=> Enable `Performance/ReverseEach` cop

config/rails.yml
Follow up of https://github.com/rails/rails/commit/4353adab89bab252521e0e191d0177ece1538fbb.
=> Enable `Lint/AmbiguousOperator` and `Lint/AmbiguousRegexpLiteral` cops

rubocop-rails_config.gemspec
https://github.com/toshimaru/rubocop-rails_config/pull/33#issuecomment-470800888
=> Add koic as an author

config/rails.yml
Follow up https://github.com/rails/rails/pull/35932.
=> Enable `Layout/SpaceBeforeComment` cop

config/rails.yml
=> Change "EnforcedStyle: rails" to "EnforcedStyle: indented_internal_methods"

config/rails.yml
Follow up https://github.com/rails/rails/pull/37121.
=> Disable `Style/BracesAroundHashParameters`

config/rails.yml
Follow up of https://github.com/rails/rails/commit/245b0377348e686445ffc65b576dc587a2c66b49.
=> Exclude tmp directory by default

config/rails.yml
Follow https://github.com/rails/rails/commit/9b8fb3fc042c1b541a4bf0ef795aaff849c2de16.
=> Enable `Layout/ClosingHeredocIndentation` cop

.travis.yml, Appraisals, config/rails.yml, gemfiles/rubocop_0.82.gemfile, rubocop-rails_config.gemspec
Fixes #68.
Follow up of https://github.com/rails/rails/pull/38980.
=> Rename `Layout/Tab` to `Layout/IndentationStyle`

config/rails.yml
Follow up to rails/rails#38992.
=> Enable `Rails/IndexBy` and `Rails/IndexWith` cops

config/rails.yml
- rubocop-packing PR: rails/rails#40185
- rails/rails#39755
=> Follow upstream rubocop changes

.travis.yml, Appraisals, gemfiles/rubocop_0.85.gemfile, gemfiles/rubocop_0.86.gemfile, gemfiles/rubocop_0.87.gemfile, gemfiles/rubocop_0.88.gemfile, gemfiles/rubocop_0.89.gemfile, gemfiles/rubocop_0.91.gemfile, gemfiles/rubocop_0.92.gemfile, gemfiles/rubocop_0.93.gemfile
ref. https://github.com/rubocop-hq/rubocop/releases/tag/v0.93.0
=> Support rubocop v0.93

config/rails.yml
Follow https://github.com/rails/rails/pull/41064.
This PR enables `Lint/DuplicateRequire` cop.
=> Enable `Lint/DuplicateRequire` cop

config/rails.yml
Follow https://github.com/rails/rails/commit/458f19a0f7c296a8d01c97a6b86821bceb130327
=> Opt out of `SuggestExtensions` message

config/rails.yml
Follow https://github.com/rails/rails/commit/6515d6985d2b537486bd9d1faa95212a508dc42c
=> Enable `Performance/BindCall` cop

config/rails.yml
Follow https://github.com/rails/rails/pull/41440.
This PR disables `Layout/FirstArgumentIndentation` cop.
=> Disable `Layout/FirstArgumentIndentation` cop

config/rails.yml
Follow https://github.com/rails/rails/commit/c4b944a
=> Enable `Performance/StringReplacement` cop

config/rails.yml
Follow https://github.com/rails/rails/commit/c0c77e2
=> Enable `Layout/EndOfLine` cop

config/rails.yml
Follow https://github.com/rails/rails/pull/42083
=> Enable `Performance/SelectMap` cop

.github/workflows/test.yml
=> Add gemfiles

config/rails.yml, rubocop-rails_config.gemspec
Follow up to https://github.com/rails/rails/pull/43032.
=> Enable `Minitest/UnreachableAssertion` cop

config/rails.yml
Follow up to https://github.com/rails/rails/pull/43170.
=> Enable `Style/ExplicitBlockArgument` cop

config/rails.yml
Follow up to https://github.com/rails/rails/pull/43374.
=> Enable `Lint/DuplicateMethods` cop

config/rails.yml
Follow up of https://github.com/rails/rails/pull/44343.
=> Enable `Lint/EnsureReturn` cop

config/rails.yml
Follow up of https://github.com/rails/rails/pull/44473.
=> Enabled `Performance/OpenStruct` cop

config/rails.yml
Follow up https://github.com/rails/rails/pull/44555.
=> Enable `Style/MapToHash` cop

config/rails.yml
follows https://github.com/rails/rails/pull/45631 change
=> Enable `Style/RedundantCondition` cop

config/rails.yml
Follow up https://github.com/rails/rails/pull/45966.
=> Enable `Minitest/AssertRaisesWithRegexpArgument` cop

config/rails.yml
Follow up https://github.com/rails/rails/pull/44547.
=> Enable `Minitest/AssertWithExpectedArgument` cop

config/rails.yml
Follow up https://github.com/rails/rails/pull/46088.
=> Enable `Minitest/SkipEnsure` cop

rubocop-rails_config.gemspec
Follow up https://github.com/rails/rails/pull/45965.
=> Require RuboCop Minitest 0.22 or higher

config/rails.yml
Follow up https://github.com/rails/rails/pull/46969.
=> Enable `Style/EvalWithLocation` cop

Rakefile, config/rails.yml, rubocop-rails_config.gemspec
ref. https://github.com/rails/rails/pull/47186
- Add [rubocop-md](https://github.com/rubocop/rubocop-md) gem
=> :gem: Add `rubocop-md` gem

config/rails.yml
Follow up https://github.com/rails/rails/pull/49628.
This PR enables `Minitest/AssertPredicate` cop.
=> Enable `Minitest/AssertPredicate` cop
